# Generated by Django 4.2.5 on 2023-09-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='style_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three'), ('four', 'Four'), ('five', 'Five'), ('six', 'Six')], default='one', max_length=10),
        ),
    ]
