# Generated by Django 4.2.5 on 2023-09-10 05:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_section_style_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Up to 4 words allowed.', regex='^(\\W*\\w+\\b\\W*){1,4}$')]),
        ),
    ]
