# Generated by Django 4.2.5 on 2023-09-11 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_noticia_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntasfrecuentes',
            name='button_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preguntasfrecuentes',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Up to 4 words allowed.', regex='^(\\W*\\w+\\b\\W*){1,4}$')]),
        ),
    ]
